#!/usr/bin/env bash
#Checks if files exist then print
#If it existx, print empty/not empty/regular/not regular.
if [ -e "School" ]
then
    echo "School file exists"
    if [ -s "School" ]
    then
	echo "School file is not empty"
    else
	echo "School file is empty"
    fi
    if [ -f "School" ]
    then
	echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
